#!/usr/bin/env python

import argparse

from App.Plot import Plot


def main():
    parser = argparse.ArgumentParser(description="")
    parser.add_argument("--config", "-c", help="Configuration file path", default="")
    parser.add_argument("--db", "-d", help="Database file", required=True)
    parser.add_argument("--whitelist", "-w", help="File of whitelisted networks (regexp)", dest="whitelist_file",
                        default=None)
    parser.add_argument("--blacklist", "-b", help="File of blacklisted networks (regexp)", dest="blacklist_file",
                        default=None)
    parser.add_argument("--mac-addr", "-m", help="Specific Mac address", dest="mac_addr", default=None)
    parser.add_argument("--plot-map", "-o", help="Write map to this file name", dest="plot_map", default=None)
    parser.add_argument("--sleep", "-s", help="Sleep offset between requests", dest="sleep", type=int, default=2)
    parser.add_argument("--debug", help="Print debugging", dest="debug", action="store_true")
    parser.add_argument("--verbose", "-v", help="Increased verbosity", dest="verbose", action="store_true")
    parser.add_argument("--dry", help="Only display database contents", dest="dry", action="store_true")
    parser.add_argument("--flush-cache", help="Flush location cache", dest="flush_cache", action="store_true")

    args = parser.parse_args()

    Plot(args).setup().run()


if __name__ != 'main':
    main()
